Added t3.micro as default fallback when non nitro instances are chose…
openshift/osd-network-verifier pull request #208
Opened 2024-01-31 21:16 UTC by luis-falcon

Added t3.micro as default fallback when non nitro instances are chose…

## What does this PR do? / Related Issues / Jira
https://issues.redhat.com/browse/OSD-20512

2024-01-31 23:14 UTC, abyrne55 requested changes
Made a few changes to make logging more consistent. Also reintroduced the  "set default if blank" bit of code, because external apps (not the CLI) will end up printing a nasty error otherwise. See [feedback.patch.txt](https://github.com/openshift/osd-network-verifier/files/14118268/feedback.patch.txt) (apply with `git am < feedback.patch.txt`)

2024-02-02 16:09 UTC, abyrne55 approved these changes
/lgtm

Tested this locally with `--instance-type p3.2xlarge` and confirmed the verifier quietly defaulted back to t3.micro. Thanks @luis-falcon!

2024-02-03 04:52 UTC, mjlshen approved these changes
/approve

2024-02-03 04:52 UTC, mjlshen commented
/label tide/merge-method-squash

2024-02-03 04:56 UTC, merged