Remove deprecated 'securityGroupId' property from createEC2InstanceInput
openshift/osd-network-verifier pull request #247
Opened 2024-07-08 19:20 UTC by AlexVulaj

Removes deprecated `securityGroupId` property from `createEc2InstanceInput` struct.

2024-07-08 22:34 UTC, abyrne55 requested changes
Unfortunately, I think there's more that has to happen here. [Consumers of the verifier](https://github.com/search?q=org%3Aopenshift+AWS.SecurityGroupId+NOT+repo%3Aopenshift%2Fosd-network-verifier+&type=code) are still setting the deprecated `SecurityGroupId` field of the `AwsEgressConfig` type instead of the `SecurityGroupIDs` field, and currently this PR leaves that deprecated field silently unhandled AFAICT. We either have to:
* preserve `AwsEgressConfig.SecurityGroupId` and replace the compatibility shim removed by this PR with another shim somewhere else
* yank `AwsEgressConfig.SecurityGroupId`, which is a breaking API change 

I'm not terribly opposed to breaking API changes at the moment, considering the verifier's next release will likely bump the x- and/or y-stream version, but we might want to be careful about changing too much all at once.

2024-07-09 14:16 UTC, AlexVulaj commented
@abyrne55 good catch on these concerns. My take is that - considering this is still in "beta" technically and only has 3 known consumers, we should update those consumers to use the new field instead and then come back to this PR. Curious to hear your thoughts or any other maintainers'!

2024-07-10 13:22 UTC, AlexVulaj commented
@abyrne55 I've updated osdctl and CAD with PRs linked in the description here. I didn't find any uses in clusters service.

2024-07-11 17:44 UTC, abyrne55 requested changes
Nice work with those consumer PRs. One more thing here: could you just remove the `securityGroupId` field of the `egressConfig` struct type on cmd/egress/cmd.go:37, as well as the line that sets up a CLI flag for it near the bottom of the same file?

2024-07-11 18:25 UTC, merged