OSD-20513: Add support for the `--noproxy` directive in `curl`
openshift/osd-network-verifier pull request #280
Opened 2024-10-23 02:53 UTC by joshbranham

## What does this PR do? / Related Issues / Jira

This adds an additional `Proxy` config to support passing `--noproxy` to `curl` when probing urls. The values passed will _not_ be proxied through the configured http/https proxy.

I opted to not update the legacy probe based on it being called "legacy" but am open to go down that route if we still have use cases for it.

I tested this with the CLI locally and ran the integration tests as well.

On the integration tests, I ran into an aws sdk issue that required bumping the dependencies.

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have tested the functionality against gcp / aws, it doesn't cause any regression
- [ ] I have added execution results to the PR's readme

## Reviewer's Checklist

- [ ] (This needs to be done after technical review) I've run the branch on my local, verified that the functionality is ok

## How to test this PR locally / Special Instructions

## Logs

2024-10-23 02:53 UTC, joshbranham commented
/label feature

2024-10-23 17:04 UTC, abyrne55 requested changes
Very nice work overall, @joshbranham, and thank you for cleaning up some smelly code in the CLI. I made a few suggestions re. passing NO_PROXY as an env. var vs. a curl flag

2024-10-23 17:04 UTC, abyrne55 commented on pkg/verifier/aws/entry_point.go
> +		"NOPROXY":          vei.Proxy.NoProxyAsString(),
```suggestion
		"NO_PROXY":          vei.Proxy.NoProxyAsString(),
```
nit: staying consistent with our other proxy-related metavars

2024-10-23 17:04 UTC, abyrne55 commented on pkg/verifier/gcp/entry_point.go
> +		"NOPROXY":          vei.Proxy.NoProxyAsString(),
```suggestion
		"NO_PROXY":          vei.Proxy.NoProxyAsString(),
```
nit: staying consistent with our other proxy-related metavars

2024-10-23 18:41 UTC, joshbranham commented
/label tide/merge-method-squash

2024-10-23 18:42 UTC, joshbranham commented
@abyrne55 addressed feedback and ran another set of tests. See below for the curl behavior as tested on it's own as well.

```
> export http_proxy=squid.corp.redhat.com:3128 https_proxy=squid.corp.redhat.com:3128 no_proxy=google.com
> curl redhat.com -w "%{json}" -Z -s -o /dev/null | jq .proxy_used
1
> curl google.com -w "%{json}" -Z -s -o /dev/null | jq .proxy_used
0
```

2024-10-24 22:29 UTC, abyrne55 commented
Tested this locally using a modified version of examples/aws/terraform/vpc-proxied-explicit. All successful. Good stuff @joshbranham. I'm approving, but before I LGTM, did we not want to put quotes around the NO_PROXY metavar in the userdata template, just in case a space sneaks in there? 

/approve

2024-10-24 22:45 UTC, joshbranham commented
> Tested this locally using a modified version of examples/aws/terraform/vpc-proxied-explicit. All successful. Good stuff @joshbranham. I'm approving, but before I LGTM, did we not want to put quotes around the NO_PROXY metavar in the userdata template, just in case a space sneaks in there?
> 
> /approve

It shouldn't be possible based on `strings.Join(slice, ",")` but I added quotes on both templates just to be sure 👍

2024-10-25 17:40 UTC, abyrne55 approved these changes
👌💯

/lgtm

2024-10-25 17:45 UTC, merged